FROM node:12-alpine AS build
WORKDIR /wh-web

COPY package.json ./
COPY package-lock.json ./
RUN ["npm", "install"]

COPY ./src ./src
COPY angular.json ./
copy ngsw-config.json ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
RUN ["npm", "install", "-g", "@angular/cli"]
RUN ["ng", "build", "--configuration=production"]

FROM nginx
WORKDIR /wh-web

COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /wh-web/dist/wh-web /usr/share/nginx/html

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
